# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ac59301ed4951d490d888740c4853fdc74ae171cecf0f51e0f586149c3438139211af6377a8abe3851f02ff38947dae68564d05e357a9106796841cf4cd3269

test:
  secret_key_base: 2c7762d0c764ce2985ffd9bc3f7017f54a9d9acebfca4ed6ca687ab0016eed42e90fa68e7d67fd584bad6c9c0765e2ec78e31fc0f714b910941570db8437fa5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
